// <auto-generated/>
// Emik.SourceGenerators.Tattoo, v2.0.7
#pragma warning disable
global using global::System;
global using global::System.Buffers;
global using global::System.Buffers.Binary;
global using global::System.Buffers.Text;
global using global::System.CodeDom;
global using global::System.CodeDom.Compiler;
global using global::System.Collections;
global using global::System.Collections.Concurrent;
global using global::System.Collections.Frozen;
global using global::System.Collections.Generic;
global using global::System.Collections.Immutable;
global using global::System.Collections.ObjectModel;
global using global::System.Collections.Specialized;
global using global::System.ComponentModel;
global using global::System.ComponentModel.DataAnnotations;
global using global::System.ComponentModel.DataAnnotations.Schema;
global using global::System.ComponentModel.Design;
global using global::System.ComponentModel.Design.Serialization;
global using global::System.Composition;
global using global::System.Composition.Convention;
global using global::System.Composition.Debugging;
global using global::System.Composition.Diagnostics;
global using global::System.Composition.Hosting;
global using global::System.Composition.Hosting.Core;
global using global::System.Composition.Hosting.Providers;
global using global::System.Composition.Hosting.Providers.CurrentScope;
global using global::System.Composition.Hosting.Providers.ExportFactory;
global using global::System.Composition.Hosting.Providers.ImportMany;
global using global::System.Composition.Hosting.Providers.Lazy;
global using global::System.Composition.Hosting.Providers.Metadata;
global using global::System.Composition.Hosting.Util;
global using global::System.Composition.Runtime;
global using global::System.Composition.Runtime.Util;
global using global::System.Composition.TypedParts;
global using global::System.Composition.TypedParts.ActivationFeatures;
global using global::System.Composition.TypedParts.Discovery;
global using global::System.Composition.TypedParts.Util;
global using global::System.Configuration;
global using global::System.Configuration.Assemblies;
global using global::System.Configuration.Internal;
global using global::System.Configuration.Provider;
global using global::System.Data;
global using global::System.Data.Common;
global using global::System.Data.Odbc;
global using global::System.Data.OleDb;
global using global::System.Data.OracleClient;
global using global::System.Data.Sql;
global using global::System.Data.SqlClient;
global using global::System.Data.SqlTypes;
global using global::System.Diagnostics;
global using global::System.Diagnostics.CodeAnalysis;
global using global::System.Diagnostics.Contracts;
global using global::System.Diagnostics.Eventing;
global using global::System.Diagnostics.Eventing.Reader;
global using global::System.Diagnostics.Metrics;
global using global::System.Diagnostics.PerformanceData;
global using global::System.Diagnostics.SymbolStore;
global using global::System.Diagnostics.Tracing;
global using global::System.DirectoryServices;
global using global::System.Drawing;
global using global::System.Drawing.Configuration;
global using global::System.Drawing.Design;
global using global::System.Drawing.Drawing2D;
global using global::System.Drawing.Imaging;
global using global::System.Drawing.Printing;
global using global::System.Drawing.Text;
global using global::System.Dynamic;
global using global::System.Formats;
global using global::System.Formats.Asn1;
global using global::System.Globalization;
global using global::System.IO;
global using global::System.IO.Compression;
global using global::System.IO.Enumeration;
global using global::System.IO.Hashing;
global using global::System.IO.Internal;
global using global::System.IO.IsolatedStorage;
global using global::System.IO.MemoryMappedFiles;
global using global::System.IO.Packaging;
global using global::System.IO.Pipelines;
global using global::System.IO.Pipes;
global using global::System.IO.Ports;
global using global::System.Linq;
global using global::System.Linq.Expressions;
global using global::System.Media;
global using global::System.Net;
global using global::System.Net.Cache;
global using global::System.Net.Http;
global using global::System.Net.Http.Headers;
global using global::System.Net.Http.Json;
global using global::System.Net.Mail;
global using global::System.Net.Mime;
global using global::System.Net.NetworkInformation;
global using global::System.Net.PeerToPeer;
global using global::System.Net.PeerToPeer.Collaboration;
global using global::System.Net.Security;
global using global::System.Net.Sockets;
global using global::System.Net.WebSockets;
global using global::System.Numerics;
global using global::System.Numerics.Hashing;
global using global::System.Reflection;
global using global::System.Reflection.Emit;
global using global::System.Reflection.Internal;
global using global::System.Reflection.Metadata;
global using global::System.Reflection.Metadata.Ecma335;
global using global::System.Reflection.PortableExecutable;
global using global::System.Resources;
global using global::System.Runtime;
global using global::System.Runtime.CompilerServices;
global using global::System.Runtime.ConstrainedExecution;
global using global::System.Runtime.ExceptionServices;
global using global::System.Runtime.InteropServices;
global using global::System.Runtime.InteropServices.ComTypes;
global using global::System.Runtime.InteropServices.ObjectiveC;
global using global::System.Runtime.Intrinsics;
global using global::System.Runtime.Intrinsics.Arm;
global using global::System.Runtime.Intrinsics.X86;
global using global::System.Runtime.Loader;
global using global::System.Runtime.Remoting;
global using global::System.Runtime.Serialization;
global using global::System.Runtime.Serialization.Formatters;
global using global::System.Runtime.Serialization.Formatters.Binary;
global using global::System.Runtime.Serialization.Json;
global using global::System.Runtime.Versioning;
global using global::System.Security;
global using global::System.Security.AccessControl;
global using global::System.Security.Authentication;
global using global::System.Security.Authentication.ExtendedProtection;
global using global::System.Security.Claims;
global using global::System.Security.Cryptography;
global using global::System.Security.Cryptography.Pkcs;
global using global::System.Security.Cryptography.X509Certificates;
global using global::System.Security.Cryptography.Xml;
global using global::System.Security.Permissions;
global using global::System.Security.Policy;
global using global::System.Security.Principal;
global using global::System.ServiceModel;
global using global::System.ServiceModel.Syndication;
global using global::System.ServiceProcess;
global using global::System.Text;
global using global::System.Text.Encodings;
global using global::System.Text.Encodings.Web;
global using global::System.Text.Json;
global using global::System.Text.Json.Nodes;
global using global::System.Text.Json.Serialization;
global using global::System.Text.Json.Serialization.Metadata;
global using global::System.Text.RegularExpressions;
global using global::System.Text.Unicode;
global using global::System.Threading;
global using global::System.Threading.Channels;
global using global::System.Threading.Tasks;
global using global::System.Threading.Tasks.Dataflow;
global using global::System.Threading.Tasks.Sources;
global using global::System.Timers;
global using global::System.Transactions;
global using global::System.Web;
global using global::System.Windows;
global using global::System.Windows.Input;
global using global::System.Windows.Markup;
global using global::System.Xaml;
global using global::System.Xaml.Permissions;
global using global::System.Xml;
global using global::System.Xml.Linq;
global using global::System.Xml.Resolvers;
global using global::System.Xml.Schema;
global using global::System.Xml.Serialization;
global using global::System.Xml.XPath;
global using global::System.Xml.Xsl;
global using global::AsmResolver;
global using global::AsmResolver.Collections;
global using global::AsmResolver.DotNet;
global using global::AsmResolver.DotNet.Builder;
global using global::AsmResolver.DotNet.Builder.Discovery;
global using global::AsmResolver.DotNet.Builder.Metadata;
global using global::AsmResolver.DotNet.Builder.Resources;
global using global::AsmResolver.DotNet.Builder.VTableFixups;
global using global::AsmResolver.DotNet.Bundles;
global using global::AsmResolver.DotNet.Cloning;
global using global::AsmResolver.DotNet.Code;
global using global::AsmResolver.DotNet.Code.Cil;
global using global::AsmResolver.DotNet.Code.Native;
global using global::AsmResolver.DotNet.Collections;
global using global::AsmResolver.DotNet.Config;
global using global::AsmResolver.DotNet.Config.Json;
global using global::AsmResolver.DotNet.Memory;
global using global::AsmResolver.DotNet.Resources;
global using global::AsmResolver.DotNet.Serialized;
global using global::AsmResolver.DotNet.Signatures;
global using global::AsmResolver.DotNet.Signatures.Parsing;
global using global::AsmResolver.IO;
global using global::AsmResolver.PE;
global using global::AsmResolver.PE.Builder;
global using global::AsmResolver.PE.Certificates;
global using global::AsmResolver.PE.Code;
global using global::AsmResolver.PE.Debug;
global using global::AsmResolver.PE.Debug.Builder;
global using global::AsmResolver.PE.DotNet;
global using global::AsmResolver.PE.DotNet.Cil;
global using global::AsmResolver.PE.DotNet.Metadata;
global using global::AsmResolver.PE.DotNet.Metadata.Tables;
global using global::AsmResolver.PE.DotNet.ReadyToRun;
global using global::AsmResolver.PE.DotNet.Resources;
global using global::AsmResolver.PE.DotNet.StrongName;
global using global::AsmResolver.PE.DotNet.VTableFixups;
global using global::AsmResolver.PE.Exceptions;
global using global::AsmResolver.PE.Exports;
global using global::AsmResolver.PE.Exports.Builder;
global using global::AsmResolver.PE.File;
global using global::AsmResolver.PE.Imports;
global using global::AsmResolver.PE.Imports.Builder;
global using global::AsmResolver.PE.Platforms;
global using global::AsmResolver.PE.Relocations;
global using global::AsmResolver.PE.Relocations.Builder;
global using global::AsmResolver.PE.Tls;
global using global::AsmResolver.PE.Win32Resources;
global using global::AsmResolver.PE.Win32Resources.Builder;
global using global::AsmResolver.Patching;
global using global::AsmResolver.Shims;
global using global::AssetRipper;
global using global::AssetRipper.Primitives;
global using global::AssetRipper.Primitives.Extensions;
global using global::AssetsTools;
global using global::AssetsTools.NET;
global using global::AssetsTools.NET.Extra;
global using global::AssetsTools.NET.Extra.Decompressors;
global using global::AssetsTools.NET.Extra.Decompressors.LZ4;
global using global::CommunityToolkit;
global using global::CommunityToolkit.Common;
global using global::CommunityToolkit.Common.Collections;
global using global::CommunityToolkit.Common.Deferred;
global using global::CommunityToolkit.Common.Extensions;
global using global::CommunityToolkit.Common.Helpers;
global using global::CommunityToolkit.Diagnostics;
global using global::CommunityToolkit.Helpers;
global using global::CommunityToolkit.HighPerformance;
global using global::CommunityToolkit.HighPerformance.Buffers;
global using global::CommunityToolkit.HighPerformance.Buffers.Internals;
global using global::CommunityToolkit.HighPerformance.Buffers.Internals.Interfaces;
global using global::CommunityToolkit.HighPerformance.Buffers.Views;
global using global::CommunityToolkit.HighPerformance.Enumerables;
global using global::CommunityToolkit.HighPerformance.Helpers;
global using global::CommunityToolkit.HighPerformance.Helpers.Internals;
global using global::CommunityToolkit.HighPerformance.Memory;
global using global::CommunityToolkit.HighPerformance.Memory.Internals;
global using global::CommunityToolkit.HighPerformance.Memory.Views;
global using global::CommunityToolkit.HighPerformance.Streams;
global using global::DotNetProjectFile;
global using global::DotNetProjectFile.Analyzers;
global using global::DotNetProjectFile.Analyzers.EditorConfig;
global using global::DotNetProjectFile.Analyzers.Generic;
global using global::DotNetProjectFile.Analyzers.Helpers;
global using global::DotNetProjectFile.Analyzers.Ini;
global using global::DotNetProjectFile.Analyzers.MsBuild;
global using global::DotNetProjectFile.Analyzers.Resx;
global using global::DotNetProjectFile.Analyzers.Slnx;
global using global::DotNetProjectFile.BuildAgents;
global using global::DotNetProjectFile.Caching;
global using global::DotNetProjectFile.CodeAnalysis;
global using global::DotNetProjectFile.Collections;
global using global::DotNetProjectFile.Conversion;
global using global::DotNetProjectFile.Diagnostics;
global using global::DotNetProjectFile.EditorConfig;
global using global::DotNetProjectFile.Git;
global using global::DotNetProjectFile.IO;
global using global::DotNetProjectFile.Ini;
global using global::DotNetProjectFile.Licensing;
global using global::DotNetProjectFile.MsBuild;
global using global::DotNetProjectFile.MsBuild.CSharp;
global using global::DotNetProjectFile.MsBuild.Conversion;
global using global::DotNetProjectFile.MsBuild.VisualBasic;
global using global::DotNetProjectFile.Navigation;
global using global::DotNetProjectFile.NuGet;
global using global::DotNetProjectFile.NuGet.Packaging;
global using global::DotNetProjectFile.Parsing;
global using global::DotNetProjectFile.Parsing.Internal;
global using global::DotNetProjectFile.Resx;
global using global::DotNetProjectFile.Slnx;
global using global::DotNetProjectFile.Syntax;
global using global::DotNetProjectFile.Text;
global using global::DotNetProjectFile.Text.Globbing;
global using global::DotNetProjectFile.Xml;
global using global::Emik;
global using global::Emik.Morsels;
global using global::FxResources;
global using global::FxResources.Microsoft;
global using global::FxResources.Microsoft.Extensions;
global using global::FxResources.Microsoft.Extensions.Logging;
global using global::FxResources.Microsoft.Extensions.Logging.Abstractions;
global using global::FxResources.System;
global using global::FxResources.System.Collections;
global using global::FxResources.System.Collections.Immutable;
global using global::FxResources.System.Composition;
global using global::FxResources.System.Composition.Convention;
global using global::FxResources.System.Composition.Hosting;
global using global::FxResources.System.Composition.Runtime;
global using global::FxResources.System.Composition.TypedParts;
global using global::FxResources.System.Configuration;
global using global::FxResources.System.Configuration.ConfigurationManager;
global using global::FxResources.System.IO;
global using global::FxResources.System.IO.Pipelines;
global using global::FxResources.System.Reflection;
global using global::FxResources.System.Reflection.Metadata;
global using global::FxResources.System.Security;
global using global::FxResources.System.Security.Cryptography;
global using global::FxResources.System.Security.Cryptography.ProtectedData;
global using global::FxResources.System.Security.Permissions;
global using global::FxResources.System.Text;
global using global::FxResources.System.Text.Encoding;
global using global::FxResources.System.Text.Encoding.CodePages;
global using global::FxResources.System.Threading;
global using global::FxResources.System.Threading.Channels;
global using global::FxResources.System.Windows;
global using global::FxResources.System.Windows.Extensions;
global using global::Grammr;
global using global::Grammr.Lexers;
global using global::Grammr.Parsers;
global using global::Grammr.Syntax;
global using global::Grammr.Text;
global using global::Harmony;
global using global::HarmonyLib;
global using global::HarmonyLib.Internal;
global using global::HarmonyLib.Internal.Patching;
global using global::HarmonyLib.Internal.RuntimeFixes;
global using global::HarmonyLib.Internal.Util;
global using global::HarmonyLib.Public;
global using global::HarmonyLib.Public.Patching;
global using global::HarmonyLib.Tools;
global using global::ILMerge;
global using global::Iced;
global using global::Iced.Intel;
global using global::Iced.Intel.BlockEncoderInternal;
global using global::Iced.Intel.DecoderInternal;
global using global::Iced.Intel.EncoderInternal;
global using global::Iced.Intel.FastFormatterInternal;
global using global::Iced.Intel.FormatterInternal;
global using global::Iced.Intel.GasFormatterInternal;
global using global::Iced.Intel.InstructionInfoInternal;
global using global::Iced.Intel.IntelFormatterInternal;
global using global::Iced.Intel.Internal;
global using global::Iced.Intel.MasmFormatterInternal;
global using global::Iced.Intel.NasmFormatterInternal;
global using global::Il2Cpp;
global using global::Il2CppAOT;
global using global::Il2CppInternal;
global using global::Il2CppInternal.Cryptography;
global using global::Il2CppInternal.Runtime;
global using global::Il2CppInternal.Runtime.Augments;
global using global::Il2CppInternal.Threading;
global using global::Il2CppInternal.Threading.Tasks;
global using global::Il2CppInternal.Threading.Tasks.Tracing;
global using global::Il2CppInterop;
global using global::Il2CppInterop.Common;
global using global::Il2CppInterop.Common.Attributes;
global using global::Il2CppInterop.Common.Extensions;
global using global::Il2CppInterop.Common.Host;
global using global::Il2CppInterop.Common.Maps;
global using global::Il2CppInterop.Common.XrefScans;
global using global::Il2CppInterop.Generator;
global using global::Il2CppInterop.Generator.Contexts;
global using global::Il2CppInterop.Generator.Extensions;
global using global::Il2CppInterop.Generator.MetadataAccess;
global using global::Il2CppInterop.Generator.Passes;
global using global::Il2CppInterop.Generator.Runners;
global using global::Il2CppInterop.Generator.Utils;
global using global::Il2CppInterop.Generator.XrefScans;
global using global::Il2CppInterop.HarmonySupport;
global using global::Il2CppInterop.Runtime;
global using global::Il2CppInterop.Runtime.Attributes;
global using global::Il2CppInterop.Runtime.Injection;
global using global::Il2CppInterop.Runtime.Injection.Hooks;
global using global::Il2CppInterop.Runtime.InteropTypes;
global using global::Il2CppInterop.Runtime.InteropTypes.Arrays;
global using global::Il2CppInterop.Runtime.InteropTypes.Fields;
global using global::Il2CppInterop.Runtime.Runtime;
global using global::Il2CppInterop.Runtime.Runtime.VersionSpecific;
global using global::Il2CppInterop.Runtime.Runtime.VersionSpecific.Assembly;
global using global::Il2CppInterop.Runtime.Runtime.VersionSpecific.AssemblyName;
global using global::Il2CppInterop.Runtime.Runtime.VersionSpecific.Class;
global using global::Il2CppInterop.Runtime.Runtime.VersionSpecific.EventInfo;
global using global::Il2CppInterop.Runtime.Runtime.VersionSpecific.Exception;
global using global::Il2CppInterop.Runtime.Runtime.VersionSpecific.FieldInfo;
global using global::Il2CppInterop.Runtime.Runtime.VersionSpecific.Image;
global using global::Il2CppInterop.Runtime.Runtime.VersionSpecific.MethodInfo;
global using global::Il2CppInterop.Runtime.Runtime.VersionSpecific.ParameterInfo;
global using global::Il2CppInterop.Runtime.Runtime.VersionSpecific.PropertyInfo;
global using global::Il2CppInterop.Runtime.Runtime.VersionSpecific.Type;
global using global::Il2CppInterop.Runtime.Startup;
global using global::Il2CppInterop.Runtime.XrefScans;
global using global::Il2CppJetBrains;
global using global::Il2CppJetBrains.Annotations;
global using global::Il2CppMicrosoft;
global using global::Il2CppMicrosoft.CodeAnalysis;
global using global::Il2CppMicrosoft.Win32;
global using global::Il2CppMicrosoft.Win32.SafeHandles;
global using global::Il2CppMono;
global using global::Il2CppMono.Globalization;
global using global::Il2CppMono.Globalization.Unicode;
global using global::Il2CppMono.Interop;
global using global::Il2CppMono.Security;
global using global::Il2CppMono.Security.Cryptography;
global using global::Il2CppMono.Xml;
global using global::Il2CppTMPro;
global using global::Il2CppTMPro.SpriteAssetUtilities;
global using global::Il2CppVarietyFX;
global using global::Il2Cppcom;
global using global::Il2Cppcom.cyborgAssets;
global using global::Il2Cppcom.cyborgAssets.inspectorButtonPro;
global using global::Il2Cppcom.cyborgAssets.internalIBP;
global using global::Il2Cppcom.cyborgAssets.internalIBPExample;
global using global::InlineIL;
global using global::InlineMethod;
global using global::Internal;
global using global::Internal.Cryptography;
global using global::JetBrains;
global using global::JetBrains.Annotations;
global using global::LZ4ps;
global using global::LocalsInit;
global using global::MelonLoader;
global using global::MelonLoader.Assertions;
global using global::MelonLoader.Bootstrap;
global using global::MelonLoader.CoreClrUtils;
global using global::MelonLoader.Fixes;
global using global::MelonLoader.ICSharpCode;
global using global::MelonLoader.ICSharpCode.SharpZipLib;
global using global::MelonLoader.ICSharpCode.SharpZipLib.BZip2;
global using global::MelonLoader.ICSharpCode.SharpZipLib.Checksum;
global using global::MelonLoader.ICSharpCode.SharpZipLib.Core;
global using global::MelonLoader.ICSharpCode.SharpZipLib.Encryption;
global using global::MelonLoader.ICSharpCode.SharpZipLib.GZip;
global using global::MelonLoader.ICSharpCode.SharpZipLib.Lzw;
global using global::MelonLoader.ICSharpCode.SharpZipLib.Tar;
global using global::MelonLoader.ICSharpCode.SharpZipLib.Zip;
global using global::MelonLoader.ICSharpCode.SharpZipLib.Zip.Compression;
global using global::MelonLoader.ICSharpCode.SharpZipLib.Zip.Compression.Streams;
global using global::MelonLoader.InternalUtils;
global using global::MelonLoader.Lemons;
global using global::MelonLoader.Lemons.Cryptography;
global using global::MelonLoader.Logging;
global using global::MelonLoader.Melons;
global using global::MelonLoader.Modules;
global using global::MelonLoader.MonoInternals;
global using global::MelonLoader.NativeHost;
global using global::MelonLoader.NativeUtils;
global using global::MelonLoader.NativeUtils.PEParser;
global using global::MelonLoader.Pastel;
global using global::MelonLoader.Preferences;
global using global::MelonLoader.Preferences.IO;
global using global::MelonLoader.Resolver;
global using global::MelonLoader.TinyJSON;
global using global::MelonLoader.Utils;
global using global::Microsoft;
global using global::Microsoft.CSharp;
global using global::Microsoft.CSharp.RuntimeBinder;
global using global::Microsoft.Cci;
global using global::Microsoft.Cci.Pdb;
global using global::Microsoft.CodeAnalysis;
global using global::Microsoft.CodeAnalysis.AddImport;
global using global::Microsoft.CodeAnalysis.CaseCorrection;
global using global::Microsoft.CodeAnalysis.ChangeNamespace;
global using global::Microsoft.CodeAnalysis.Classification;
global using global::Microsoft.CodeAnalysis.Classification.Classifiers;
global using global::Microsoft.CodeAnalysis.CodeActions;
global using global::Microsoft.CodeAnalysis.CodeCleanup;
global using global::Microsoft.CodeAnalysis.CodeCleanup.Providers;
global using global::Microsoft.CodeAnalysis.CodeFixes;
global using global::Microsoft.CodeAnalysis.CodeFixesAndRefactorings;
global using global::Microsoft.CodeAnalysis.CodeGen;
global using global::Microsoft.CodeAnalysis.CodeGeneration;
global using global::Microsoft.CodeAnalysis.CodeRefactorings;
global using global::Microsoft.CodeAnalysis.CodeStyle;
global using global::Microsoft.CodeAnalysis.Collections;
global using global::Microsoft.CodeAnalysis.Collections.Internal;
global using global::Microsoft.CodeAnalysis.Debugging;
global using global::Microsoft.CodeAnalysis.Diagnostics;
global using global::Microsoft.CodeAnalysis.Diagnostics.Analyzers;
global using global::Microsoft.CodeAnalysis.Diagnostics.Analyzers.NamingStyles;
global using global::Microsoft.CodeAnalysis.Diagnostics.Telemetry;
global using global::Microsoft.CodeAnalysis.Differencing;
global using global::Microsoft.CodeAnalysis.Editing;
global using global::Microsoft.CodeAnalysis.EditorConfig;
global using global::Microsoft.CodeAnalysis.EditorConfig.Parsing;
global using global::Microsoft.CodeAnalysis.EditorConfig.Parsing.NamingStyles;
global using global::Microsoft.CodeAnalysis.EmbeddedLanguages;
global using global::Microsoft.CodeAnalysis.EmbeddedLanguages.Common;
global using global::Microsoft.CodeAnalysis.EmbeddedLanguages.VirtualChars;
global using global::Microsoft.CodeAnalysis.Emit;
global using global::Microsoft.CodeAnalysis.Emit.EditAndContinue;
global using global::Microsoft.CodeAnalysis.Emit.NoPia;
global using global::Microsoft.CodeAnalysis.ErrorLogger;
global using global::Microsoft.CodeAnalysis.ErrorReporting;
global using global::Microsoft.CodeAnalysis.Extensions;
global using global::Microsoft.CodeAnalysis.ExternalAccess;
global using global::Microsoft.CodeAnalysis.ExternalAccess.Pythia;
global using global::Microsoft.CodeAnalysis.ExternalAccess.Pythia.Api;
global using global::Microsoft.CodeAnalysis.ExternalAccess.UnitTesting;
global using global::Microsoft.CodeAnalysis.ExternalAccess.UnitTesting.Api;
global using global::Microsoft.CodeAnalysis.ExternalAccess.VSTypeScript;
global using global::Microsoft.CodeAnalysis.ExternalAccess.VSTypeScript.Api;
global using global::Microsoft.CodeAnalysis.ExtractMethod;
global using global::Microsoft.CodeAnalysis.FindSymbols;
global using global::Microsoft.CodeAnalysis.FindSymbols.FindReferences;
global using global::Microsoft.CodeAnalysis.FindSymbols.Finders;
global using global::Microsoft.CodeAnalysis.FindSymbols.SymbolTree;
global using global::Microsoft.CodeAnalysis.FlowAnalysis;
global using global::Microsoft.CodeAnalysis.FlowAnalysis.SymbolUsageAnalysis;
global using global::Microsoft.CodeAnalysis.Formatting;
global using global::Microsoft.CodeAnalysis.Formatting.Rules;
global using global::Microsoft.CodeAnalysis.GeneratedCodeRecognition;
global using global::Microsoft.CodeAnalysis.Host;
global using global::Microsoft.CodeAnalysis.Host.Mef;
global using global::Microsoft.CodeAnalysis.Indentation;
global using global::Microsoft.CodeAnalysis.InitializeParameter;
global using global::Microsoft.CodeAnalysis.Internal;
global using global::Microsoft.CodeAnalysis.Internal.Log;
global using global::Microsoft.CodeAnalysis.InternalUtilities;
global using global::Microsoft.CodeAnalysis.Interop;
global using global::Microsoft.CodeAnalysis.LanguageService;
global using global::Microsoft.CodeAnalysis.LanguageService.TypeInferenceService;
global using global::Microsoft.CodeAnalysis.MoveDeclarationNearReference;
global using global::Microsoft.CodeAnalysis.NamingStyles;
global using global::Microsoft.CodeAnalysis.Notification;
global using global::Microsoft.CodeAnalysis.ObsoleteSymbol;
global using global::Microsoft.CodeAnalysis.Operations;
global using global::Microsoft.CodeAnalysis.Options;
global using global::Microsoft.CodeAnalysis.OrganizeImports;
global using global::Microsoft.CodeAnalysis.Packaging;
global using global::Microsoft.CodeAnalysis.PatternMatching;
global using global::Microsoft.CodeAnalysis.PooledObjects;
global using global::Microsoft.CodeAnalysis.Precedence;
global using global::Microsoft.CodeAnalysis.Progress;
global using global::Microsoft.CodeAnalysis.ProjectSystem;
global using global::Microsoft.CodeAnalysis.ReassignedVariable;
global using global::Microsoft.CodeAnalysis.Recommendations;
global using global::Microsoft.CodeAnalysis.Remote;
global using global::Microsoft.CodeAnalysis.RemoveUnnecessaryImports;
global using global::Microsoft.CodeAnalysis.Rename;
global using global::Microsoft.CodeAnalysis.Rename.ConflictEngine;
global using global::Microsoft.CodeAnalysis.ReplaceDiscardDeclarationsWithAssignments;
global using global::Microsoft.CodeAnalysis.RuntimeMembers;
global using global::Microsoft.CodeAnalysis.SQLite;
global using global::Microsoft.CodeAnalysis.SQLite.Interop;
global using global::Microsoft.CodeAnalysis.SQLite.v2;
global using global::Microsoft.CodeAnalysis.SQLite.v2.Interop;
global using global::Microsoft.CodeAnalysis.SemanticModelReuse;
global using global::Microsoft.CodeAnalysis.Serialization;
global using global::Microsoft.CodeAnalysis.Shared;
global using global::Microsoft.CodeAnalysis.Shared.CodeStyle;
global using global::Microsoft.CodeAnalysis.Shared.Collections;
global using global::Microsoft.CodeAnalysis.Shared.Extensions;
global using global::Microsoft.CodeAnalysis.Shared.Extensions.ContextQuery;
global using global::Microsoft.CodeAnalysis.Shared.Helpers;
global using global::Microsoft.CodeAnalysis.Shared.Helpers.RemoveUnnecessaryImports;
global using global::Microsoft.CodeAnalysis.Shared.Naming;
global using global::Microsoft.CodeAnalysis.Shared.TestHooks;
global using global::Microsoft.CodeAnalysis.Shared.Utilities;
global using global::Microsoft.CodeAnalysis.Simplification;
global using global::Microsoft.CodeAnalysis.Simplification.Simplifiers;
global using global::Microsoft.CodeAnalysis.SolutionCrawler;
global using global::Microsoft.CodeAnalysis.SourceGeneration;
global using global::Microsoft.CodeAnalysis.SourceGeneratorTelemetry;
global using global::Microsoft.CodeAnalysis.Storage;
global using global::Microsoft.CodeAnalysis.SymbolDisplay;
global using global::Microsoft.CodeAnalysis.SymbolSearch;
global using global::Microsoft.CodeAnalysis.Symbols;
global using global::Microsoft.CodeAnalysis.Syntax;
global using global::Microsoft.CodeAnalysis.Syntax.InternalSyntax;
global using global::Microsoft.CodeAnalysis.Tags;
global using global::Microsoft.CodeAnalysis.TaskList;
global using global::Microsoft.CodeAnalysis.Telemetry;
global using global::Microsoft.CodeAnalysis.Text;
global using global::Microsoft.CodeAnalysis.UnitTests;
global using global::Microsoft.CodeAnalysis.Utilities;
global using global::Microsoft.CodeAnalysis.VisualBasic;
global using global::Microsoft.CodeAnalysis.VisualBasic.CodeGeneration;
global using global::Microsoft.CodeAnalysis.VisualBasic.CodeStyle;
global using global::Microsoft.CodeAnalysis.VisualBasic.Formatting;
global using global::Microsoft.CodeAnalysis.VisualBasic.Simplification;
global using global::Microsoft.CodeAnalysis.Workspaces;
global using global::Microsoft.CodeAnalysis.Workspaces.Diagnostics;
global using global::Microsoft.CodeAnalysis.Workspaces.ProjectSystem;
global using global::Microsoft.DiaSymReader;
global using global::Microsoft.Diagnostics;
global using global::Microsoft.Diagnostics.NETCore;
global using global::Microsoft.Diagnostics.NETCore.Client;
global using global::Microsoft.Diagnostics.NETCore.Client.WebSocketServer;
global using global::Microsoft.Diagnostics.Runtime;
global using global::Microsoft.Diagnostics.Runtime.AbstractDac;
global using global::Microsoft.Diagnostics.Runtime.DacImplementation;
global using global::Microsoft.Diagnostics.Runtime.DacInterface;
global using global::Microsoft.Diagnostics.Runtime.DataReaders;
global using global::Microsoft.Diagnostics.Runtime.DataReaders.Implementation;
global using global::Microsoft.Diagnostics.Runtime.DataReaders.Windows;
global using global::Microsoft.Diagnostics.Runtime.DbgEng;
global using global::Microsoft.Diagnostics.Runtime.Extensions;
global using global::Microsoft.Diagnostics.Runtime.Implementation;
global using global::Microsoft.Diagnostics.Runtime.Interfaces;
global using global::Microsoft.Diagnostics.Runtime.MacOS;
global using global::Microsoft.Diagnostics.Runtime.MacOS.Structs;
global using global::Microsoft.Diagnostics.Runtime.Utilities;
global using global::Microsoft.Diagnostics.Runtime.Windows;
global using global::Microsoft.Extensions;
global using global::Microsoft.Extensions.Configuration;
global using global::Microsoft.Extensions.Configuration.Binder;
global using global::Microsoft.Extensions.Configuration.Memory;
global using global::Microsoft.Extensions.DependencyInjection;
global using global::Microsoft.Extensions.DependencyInjection.Abstractions;
global using global::Microsoft.Extensions.DependencyInjection.Extensions;
global using global::Microsoft.Extensions.Internal;
global using global::Microsoft.Extensions.Logging;
global using global::Microsoft.Extensions.Logging.Abstractions;
global using global::Microsoft.Extensions.Options;
global using global::Microsoft.Extensions.Primitives;
global using global::Microsoft.SqlServer;
global using global::Microsoft.SqlServer.Server;
global using global::Microsoft.VisualBasic;
global using global::Microsoft.VisualBasic.CompilerServices;
global using global::Microsoft.VisualBasic.FileIO;
global using global::Microsoft.Win32;
global using global::Microsoft.Win32.SafeHandles;
global using global::Mono;
global using global::Mono.Cecil;
global using global::Mono.Cecil.Cil;
global using global::Mono.Cecil.Mdb;
global using global::Mono.Cecil.Metadata;
global using global::Mono.Cecil.PE;
global using global::Mono.Cecil.Pdb;
global using global::Mono.Cecil.Rocks;
global using global::Mono.Collections;
global using global::Mono.Collections.Generic;
global using global::Mono.CompilerServices;
global using global::Mono.CompilerServices.SymbolWriter;
global using global::Mono.Security;
global using global::Mono.Security.Cryptography;
global using global::MonoMod;
global using global::MonoMod.Backports;
global using global::MonoMod.Backports.ILHelpers;
global using global::MonoMod.Cil;
global using global::MonoMod.InlineRT;
global using global::MonoMod.ModInterop;
global using global::MonoMod.RuntimeDetour;
global using global::MonoMod.RuntimeDetour.HookGen;
global using global::MonoMod.RuntimeDetour.Platforms;
global using global::MonoMod.SourceGen;
global using global::MonoMod.SourceGen.Attributes;
global using global::MonoMod.Utils;
global using global::MonoMod.Utils.Cil;
global using global::Newtonsoft;
global using global::Newtonsoft.Json;
global using global::Newtonsoft.Json.Bson;
global using global::Newtonsoft.Json.Converters;
global using global::Newtonsoft.Json.Linq;
global using global::Newtonsoft.Json.Linq.JsonPath;
global using global::Newtonsoft.Json.Schema;
global using global::Newtonsoft.Json.Serialization;
global using global::Newtonsoft.Json.Utilities;
global using global::NullGuard;
global using global::NullGuard.CodeAnalysis;
global using global::Roslyn;
global using global::Roslyn.Utilities;
global using global::Scifa;
global using global::Scifa.CheckedExceptions;
global using global::Scifa.CheckedExceptions.Attributes;
global using global::Semver;
global using global::SevenZip;
global using global::SevenZip.Buffer;
global using global::SevenZip.CommandLineParser;
global using global::SevenZip.Compression;
global using global::SevenZip.Compression.LZ;
global using global::SevenZip.Compression.LZMA;
global using global::SevenZip.Compression.RangeCoder;
global using global::Tomlet;
global using global::Tomlet.Attributes;
global using global::Tomlet.Exceptions;
global using global::Tomlet.Extensions;
global using global::Tomlet.Models;
global using global::Trowel;
global using global::Unity;
global using global::Unity.Audio;
global using global::Unity.Baselib;
global using global::Unity.Baselib.LowLevel;
global using global::Unity.Burst;
global using global::Unity.Burst.CompilerServices;
global using global::Unity.Burst.Intrinsics;
global using global::Unity.Burst.LowLevel;
global using global::Unity.Collections;
global using global::Unity.Collections.LowLevel;
global using global::Unity.Collections.LowLevel.Unsafe;
global using global::Unity.Collections.LowLevel.Unsafe.NotBurstCompatible;
global using global::Unity.Collections.NotBurstCompatible;
global using global::Unity.Curl;
global using global::Unity.IL2CPP;
global using global::Unity.IL2CPP.CompilerServices;
global using global::Unity.IL2CPP.Metadata;
global using global::Unity.IO;
global using global::Unity.IO.Archive;
global using global::Unity.IO.LowLevel;
global using global::Unity.IO.LowLevel.Unsafe;
global using global::Unity.Jobs;
global using global::Unity.Jobs.LowLevel;
global using global::Unity.Jobs.LowLevel.Unsafe;
global using global::Unity.Loading;
global using global::Unity.Mathematics;
global using global::Unity.Mathematics.Geometry;
global using global::Unity.Profiling;
global using global::Unity.Profiling.LowLevel;
global using global::Unity.Profiling.LowLevel.Unsafe;
global using global::Unity.Profiling.Memory;
global using global::Unity.Properties;
global using global::Unity.Properties.Internal;
global using global::Unity.SpriteShape;
global using global::Unity.SpriteShape.External;
global using global::Unity.SpriteShape.External.LibTessDotNet;
global using global::Unity.TLS;
global using global::Unity.TLS.LowLevel;
global using global::UnityEditor;
global using global::UnityEditor.Experimental;
global using global::UnityEditor.Rendering;
global using global::UnityEditor.Rendering.BuiltIn;
global using global::UnityEditor.Rendering.BuiltIn.ShaderGraph;
global using global::UnityEditor.Rendering.Universal;
global using global::UnityEngine;
global using global::UnityEngine.AI;
global using global::UnityEngine.Accessibility;
global using global::UnityEngine.Advertisements;
global using global::UnityEngine.Analytics;
global using global::UnityEngine.Android;
global using global::UnityEngine.Animations;
global using global::UnityEngine.Apple;
global using global::UnityEngine.Assertions;
global using global::UnityEngine.Assertions.Comparers;
global using global::UnityEngine.Assertions.Must;
global using global::UnityEngine.Audio;
global using global::UnityEngine.Bindings;
global using global::UnityEngine.Connect;
global using global::UnityEngine.CrashReportHandler;
global using global::UnityEngine.Device;
global using global::UnityEngine.Diagnostics;
global using global::UnityEngine.EventSystems;
global using global::UnityEngine.Events;
global using global::UnityEngine.Experimental;
global using global::UnityEngine.Experimental.AI;
global using global::UnityEngine.Experimental.Animations;
global using global::UnityEngine.Experimental.AssetBundlePatching;
global using global::UnityEngine.Experimental.Audio;
global using global::UnityEngine.Experimental.GlobalIllumination;
global using global::UnityEngine.Experimental.Playables;
global using global::UnityEngine.Experimental.Rendering;
global using global::UnityEngine.Experimental.Rendering.RenderGraphModule;
global using global::UnityEngine.Experimental.Rendering.Universal;
global using global::UnityEngine.Experimental.U2D;
global using global::UnityEngine.Experimental.VFX;
global using global::UnityEngine.Experimental.Video;
global using global::UnityEngine.Experimental.XR;
global using global::UnityEngine.IO;
global using global::UnityEngine.Internal;
global using global::UnityEngine.Jobs;
global using global::UnityEngine.LowLevel;
global using global::UnityEngine.Lumin;
global using global::UnityEngine.Networking;
global using global::UnityEngine.Networking.PlayerConnection;
global using global::UnityEngine.ParticleSystemJobs;
global using global::UnityEngine.Playables;
global using global::UnityEngine.PlayerLoop;
global using global::UnityEngine.Pool;
global using global::UnityEngine.Profiling;
global using global::UnityEngine.Rendering;
global using global::UnityEngine.Rendering.LookDev;
global using global::UnityEngine.Rendering.RendererUtils;
global using global::UnityEngine.Rendering.UI;
global using global::UnityEngine.Rendering.Universal;
global using global::UnityEngine.Rendering.Universal.Internal;
global using global::UnityEngine.Rendering.Universal.LibTessDotNet;
global using global::UnityEngine.Rendering.Universal.UTess;
global using global::UnityEngine.SceneManagement;
global using global::UnityEngine.Scripting;
global using global::UnityEngine.Scripting.APIUpdating;
global using global::UnityEngine.Search;
global using global::UnityEngine.SearchService;
global using global::UnityEngine.Serialization;
global using global::UnityEngine.SocialPlatforms;
global using global::UnityEngine.SocialPlatforms.Impl;
global using global::UnityEngine.Sprites;
global using global::UnityEngine.Subsystems;
global using global::UnityEngine.SubsystemsImplementation;
global using global::UnityEngine.SubsystemsImplementation.Extensions;
global using global::UnityEngine.TerrainTools;
global using global::UnityEngine.TerrainUtils;
global using global::UnityEngine.TestTools;
global using global::UnityEngine.TextCore;
global using global::UnityEngine.TextCore.LowLevel;
global using global::UnityEngine.TextCore.Text;
global using global::UnityEngine.Tilemaps;
global using global::UnityEngine.U2D;
global using global::UnityEngine.U2D.Animation;
global using global::UnityEngine.U2D.Common;
global using global::UnityEngine.U2D.Common.UTess;
global using global::UnityEngine.UI;
global using global::UnityEngine.UI.Collections;
global using global::UnityEngine.UI.CoroutineTween;
global using global::UnityEngine.UIElements;
global using global::UnityEngine.UIElements.Collections;
global using global::UnityEngine.UIElements.Experimental;
global using global::UnityEngine.UIElements.Internal;
global using global::UnityEngine.UIElements.StyleSheets;
global using global::UnityEngine.UIElements.StyleSheets.Syntax;
global using global::UnityEngine.UIElements.UIR;
global using global::UnityEngine.UIElements.UIR.Implementation;
global using global::UnityEngine.VFX;
global using global::UnityEngine.Video;
global using global::UnityEngine.Windows;
global using global::UnityEngine.Windows.Speech;
global using global::UnityEngine.Windows.WebCam;
global using global::UnityEngine.XR;
global using global::UnityEngine.XR.Provider;
global using global::UnityEngine.XR.Tango;
global using global::UnityEngine.XR.WSA;
global using global::UnityEngine.XR.WSA.Input;
global using global::UnityEngine.Yoga;
global using global::UnityEngine._Scripting;
global using global::UnityEngine._Scripting.APIUpdating;
global using global::UnityEngineInternal;
global using global::UnityEngineInternal.Input;
global using global::UnityEngineInternal.Video;
global using global::UnityEngineInternal.XR;
global using global::UnityEngineInternal.XR.WSA;
global using global::WebSocketDotNet;
global using global::WebSocketDotNet.Http;
global using global::WebSocketDotNet.Messages;
global using global::WebSocketDotNet.Protocol;
global using global::WebSocketDotNet.Utils;
global using global::bHapticsLib;
global using global::bHapticsLib.Internal;
global using global::bHapticsLib.Internal.Models;
global using global::bHapticsLib.Internal.Models.Connection;
global using global::bHapticsLib.Internal.SimpleJSON;
global using global::bHapticsLib.Properties;

// Polyfills of namespaces in case dependencies are conditional.
namespace System { }

namespace System.Buffers { }

namespace System.Buffers.Binary { }

namespace System.Buffers.Text { }

namespace System.CodeDom { }

namespace System.CodeDom.Compiler { }

namespace System.Collections { }

namespace System.Collections.Concurrent { }

namespace System.Collections.Frozen { }

namespace System.Collections.Generic { }

namespace System.Collections.Immutable { }

namespace System.Collections.ObjectModel { }

namespace System.Collections.Specialized { }

namespace System.ComponentModel { }

namespace System.ComponentModel.DataAnnotations { }

namespace System.ComponentModel.DataAnnotations.Schema { }

namespace System.ComponentModel.Design { }

namespace System.ComponentModel.Design.Serialization { }

namespace System.Composition { }

namespace System.Composition.Convention { }

namespace System.Composition.Debugging { }

namespace System.Composition.Diagnostics { }

namespace System.Composition.Hosting { }

namespace System.Composition.Hosting.Core { }

namespace System.Composition.Hosting.Providers { }

namespace System.Composition.Hosting.Providers.CurrentScope { }

namespace System.Composition.Hosting.Providers.ExportFactory { }

namespace System.Composition.Hosting.Providers.ImportMany { }

namespace System.Composition.Hosting.Providers.Lazy { }

namespace System.Composition.Hosting.Providers.Metadata { }

namespace System.Composition.Hosting.Util { }

namespace System.Composition.Runtime { }

namespace System.Composition.Runtime.Util { }

namespace System.Composition.TypedParts { }

namespace System.Composition.TypedParts.ActivationFeatures { }

namespace System.Composition.TypedParts.Discovery { }

namespace System.Composition.TypedParts.Util { }

namespace System.Configuration { }

namespace System.Configuration.Assemblies { }

namespace System.Configuration.Internal { }

namespace System.Configuration.Provider { }

namespace System.Data { }

namespace System.Data.Common { }

namespace System.Data.Odbc { }

namespace System.Data.OleDb { }

namespace System.Data.OracleClient { }

namespace System.Data.Sql { }

namespace System.Data.SqlClient { }

namespace System.Data.SqlTypes { }

namespace System.Diagnostics { }

namespace System.Diagnostics.CodeAnalysis { }

namespace System.Diagnostics.Contracts { }

namespace System.Diagnostics.Eventing { }

namespace System.Diagnostics.Eventing.Reader { }

namespace System.Diagnostics.Metrics { }

namespace System.Diagnostics.PerformanceData { }

namespace System.Diagnostics.SymbolStore { }

namespace System.Diagnostics.Tracing { }

namespace System.DirectoryServices { }

namespace System.Drawing { }

namespace System.Drawing.Configuration { }

namespace System.Drawing.Design { }

namespace System.Drawing.Drawing2D { }

namespace System.Drawing.Imaging { }

namespace System.Drawing.Printing { }

namespace System.Drawing.Text { }

namespace System.Dynamic { }

namespace System.Formats { }

namespace System.Formats.Asn1 { }

namespace System.Globalization { }

namespace System.IO { }

namespace System.IO.Compression { }

namespace System.IO.Enumeration { }

namespace System.IO.Hashing { }

namespace System.IO.Internal { }

namespace System.IO.IsolatedStorage { }

namespace System.IO.MemoryMappedFiles { }

namespace System.IO.Packaging { }

namespace System.IO.Pipelines { }

namespace System.IO.Pipes { }

namespace System.IO.Ports { }

namespace System.Linq { }

namespace System.Linq.Expressions { }

namespace System.Media { }

namespace System.Net { }

namespace System.Net.Cache { }

namespace System.Net.Http { }

namespace System.Net.Http.Headers { }

namespace System.Net.Http.Json { }

namespace System.Net.Mail { }

namespace System.Net.Mime { }

namespace System.Net.NetworkInformation { }

namespace System.Net.PeerToPeer { }

namespace System.Net.PeerToPeer.Collaboration { }

namespace System.Net.Security { }

namespace System.Net.Sockets { }

namespace System.Net.WebSockets { }

namespace System.Numerics { }

namespace System.Numerics.Hashing { }

namespace System.Reflection { }

namespace System.Reflection.Emit { }

namespace System.Reflection.Internal { }

namespace System.Reflection.Metadata { }

namespace System.Reflection.Metadata.Ecma335 { }

namespace System.Reflection.PortableExecutable { }

namespace System.Resources { }

namespace System.Runtime { }

namespace System.Runtime.CompilerServices { }

namespace System.Runtime.ConstrainedExecution { }

namespace System.Runtime.ExceptionServices { }

namespace System.Runtime.InteropServices { }

namespace System.Runtime.InteropServices.ComTypes { }

namespace System.Runtime.InteropServices.ObjectiveC { }

namespace System.Runtime.Intrinsics { }

namespace System.Runtime.Intrinsics.Arm { }

namespace System.Runtime.Intrinsics.X86 { }

namespace System.Runtime.Loader { }

namespace System.Runtime.Remoting { }

namespace System.Runtime.Serialization { }

namespace System.Runtime.Serialization.Formatters { }

namespace System.Runtime.Serialization.Formatters.Binary { }

namespace System.Runtime.Serialization.Json { }

namespace System.Runtime.Versioning { }

namespace System.Security { }

namespace System.Security.AccessControl { }

namespace System.Security.Authentication { }

namespace System.Security.Authentication.ExtendedProtection { }

namespace System.Security.Claims { }

namespace System.Security.Cryptography { }

namespace System.Security.Cryptography.Pkcs { }

namespace System.Security.Cryptography.X509Certificates { }

namespace System.Security.Cryptography.Xml { }

namespace System.Security.Permissions { }

namespace System.Security.Policy { }

namespace System.Security.Principal { }

namespace System.ServiceModel { }

namespace System.ServiceModel.Syndication { }

namespace System.ServiceProcess { }

namespace System.Text { }

namespace System.Text.Encodings { }

namespace System.Text.Encodings.Web { }

namespace System.Text.Json { }

namespace System.Text.Json.Nodes { }

namespace System.Text.Json.Serialization { }

namespace System.Text.Json.Serialization.Metadata { }

namespace System.Text.RegularExpressions { }

namespace System.Text.Unicode { }

namespace System.Threading { }

namespace System.Threading.Channels { }

namespace System.Threading.Tasks { }

namespace System.Threading.Tasks.Dataflow { }

namespace System.Threading.Tasks.Sources { }

namespace System.Timers { }

namespace System.Transactions { }

namespace System.Web { }

namespace System.Windows { }

namespace System.Windows.Input { }

namespace System.Windows.Markup { }

namespace System.Xaml { }

namespace System.Xaml.Permissions { }

namespace System.Xml { }

namespace System.Xml.Linq { }

namespace System.Xml.Resolvers { }

namespace System.Xml.Schema { }

namespace System.Xml.Serialization { }

namespace System.Xml.XPath { }

namespace System.Xml.Xsl { }

namespace AsmResolver { }

namespace AsmResolver.Collections { }

namespace AsmResolver.DotNet { }

namespace AsmResolver.DotNet.Builder { }

namespace AsmResolver.DotNet.Builder.Discovery { }

namespace AsmResolver.DotNet.Builder.Metadata { }

namespace AsmResolver.DotNet.Builder.Resources { }

namespace AsmResolver.DotNet.Builder.VTableFixups { }

namespace AsmResolver.DotNet.Bundles { }

namespace AsmResolver.DotNet.Cloning { }

namespace AsmResolver.DotNet.Code { }

namespace AsmResolver.DotNet.Code.Cil { }

namespace AsmResolver.DotNet.Code.Native { }

namespace AsmResolver.DotNet.Collections { }

namespace AsmResolver.DotNet.Config { }

namespace AsmResolver.DotNet.Config.Json { }

namespace AsmResolver.DotNet.Memory { }

namespace AsmResolver.DotNet.Resources { }

namespace AsmResolver.DotNet.Serialized { }

namespace AsmResolver.DotNet.Signatures { }

namespace AsmResolver.DotNet.Signatures.Parsing { }

namespace AsmResolver.IO { }

namespace AsmResolver.PE { }

namespace AsmResolver.PE.Builder { }

namespace AsmResolver.PE.Certificates { }

namespace AsmResolver.PE.Code { }

namespace AsmResolver.PE.Debug { }

namespace AsmResolver.PE.Debug.Builder { }

namespace AsmResolver.PE.DotNet { }

namespace AsmResolver.PE.DotNet.Cil { }

namespace AsmResolver.PE.DotNet.Metadata { }

namespace AsmResolver.PE.DotNet.Metadata.Tables { }

namespace AsmResolver.PE.DotNet.ReadyToRun { }

namespace AsmResolver.PE.DotNet.Resources { }

namespace AsmResolver.PE.DotNet.StrongName { }

namespace AsmResolver.PE.DotNet.VTableFixups { }

namespace AsmResolver.PE.Exceptions { }

namespace AsmResolver.PE.Exports { }

namespace AsmResolver.PE.Exports.Builder { }

namespace AsmResolver.PE.File { }

namespace AsmResolver.PE.Imports { }

namespace AsmResolver.PE.Imports.Builder { }

namespace AsmResolver.PE.Platforms { }

namespace AsmResolver.PE.Relocations { }

namespace AsmResolver.PE.Relocations.Builder { }

namespace AsmResolver.PE.Tls { }

namespace AsmResolver.PE.Win32Resources { }

namespace AsmResolver.PE.Win32Resources.Builder { }

namespace AsmResolver.Patching { }

namespace AsmResolver.Shims { }

namespace AssetRipper { }

namespace AssetRipper.Primitives { }

namespace AssetRipper.Primitives.Extensions { }

namespace AssetsTools { }

namespace AssetsTools.NET { }

namespace AssetsTools.NET.Extra { }

namespace AssetsTools.NET.Extra.Decompressors { }

namespace AssetsTools.NET.Extra.Decompressors.LZ4 { }

namespace CommunityToolkit { }

namespace CommunityToolkit.Common { }

namespace CommunityToolkit.Common.Collections { }

namespace CommunityToolkit.Common.Deferred { }

namespace CommunityToolkit.Common.Extensions { }

namespace CommunityToolkit.Common.Helpers { }

namespace CommunityToolkit.Diagnostics { }

namespace CommunityToolkit.Helpers { }

namespace CommunityToolkit.HighPerformance { }

namespace CommunityToolkit.HighPerformance.Buffers { }

namespace CommunityToolkit.HighPerformance.Buffers.Internals { }

namespace CommunityToolkit.HighPerformance.Buffers.Internals.Interfaces { }

namespace CommunityToolkit.HighPerformance.Buffers.Views { }

namespace CommunityToolkit.HighPerformance.Enumerables { }

namespace CommunityToolkit.HighPerformance.Helpers { }

namespace CommunityToolkit.HighPerformance.Helpers.Internals { }

namespace CommunityToolkit.HighPerformance.Memory { }

namespace CommunityToolkit.HighPerformance.Memory.Internals { }

namespace CommunityToolkit.HighPerformance.Memory.Views { }

namespace CommunityToolkit.HighPerformance.Streams { }

namespace DotNetProjectFile { }

namespace DotNetProjectFile.Analyzers { }

namespace DotNetProjectFile.Analyzers.EditorConfig { }

namespace DotNetProjectFile.Analyzers.Generic { }

namespace DotNetProjectFile.Analyzers.Helpers { }

namespace DotNetProjectFile.Analyzers.Ini { }

namespace DotNetProjectFile.Analyzers.MsBuild { }

namespace DotNetProjectFile.Analyzers.Resx { }

namespace DotNetProjectFile.Analyzers.Slnx { }

namespace DotNetProjectFile.BuildAgents { }

namespace DotNetProjectFile.Caching { }

namespace DotNetProjectFile.CodeAnalysis { }

namespace DotNetProjectFile.Collections { }

namespace DotNetProjectFile.Conversion { }

namespace DotNetProjectFile.Diagnostics { }

namespace DotNetProjectFile.EditorConfig { }

namespace DotNetProjectFile.Git { }

namespace DotNetProjectFile.IO { }

namespace DotNetProjectFile.Ini { }

namespace DotNetProjectFile.Licensing { }

namespace DotNetProjectFile.MsBuild { }

namespace DotNetProjectFile.MsBuild.CSharp { }

namespace DotNetProjectFile.MsBuild.Conversion { }

namespace DotNetProjectFile.MsBuild.VisualBasic { }

namespace DotNetProjectFile.Navigation { }

namespace DotNetProjectFile.NuGet { }

namespace DotNetProjectFile.NuGet.Packaging { }

namespace DotNetProjectFile.Parsing { }

namespace DotNetProjectFile.Parsing.Internal { }

namespace DotNetProjectFile.Resx { }

namespace DotNetProjectFile.Slnx { }

namespace DotNetProjectFile.Syntax { }

namespace DotNetProjectFile.Text { }

namespace DotNetProjectFile.Text.Globbing { }

namespace DotNetProjectFile.Xml { }

namespace Emik { }

namespace Emik.Morsels { }

namespace FxResources { }

namespace FxResources.Microsoft { }

namespace FxResources.Microsoft.Extensions { }

namespace FxResources.Microsoft.Extensions.Logging { }

namespace FxResources.Microsoft.Extensions.Logging.Abstractions { }

namespace FxResources.System { }

namespace FxResources.System.Collections { }

namespace FxResources.System.Collections.Immutable { }

namespace FxResources.System.Composition { }

namespace FxResources.System.Composition.Convention { }

namespace FxResources.System.Composition.Hosting { }

namespace FxResources.System.Composition.Runtime { }

namespace FxResources.System.Composition.TypedParts { }

namespace FxResources.System.Configuration { }

namespace FxResources.System.Configuration.ConfigurationManager { }

namespace FxResources.System.IO { }

namespace FxResources.System.IO.Pipelines { }

namespace FxResources.System.Reflection { }

namespace FxResources.System.Reflection.Metadata { }

namespace FxResources.System.Security { }

namespace FxResources.System.Security.Cryptography { }

namespace FxResources.System.Security.Cryptography.ProtectedData { }

namespace FxResources.System.Security.Permissions { }

namespace FxResources.System.Text { }

namespace FxResources.System.Text.Encoding { }

namespace FxResources.System.Text.Encoding.CodePages { }

namespace FxResources.System.Threading { }

namespace FxResources.System.Threading.Channels { }

namespace FxResources.System.Windows { }

namespace FxResources.System.Windows.Extensions { }

namespace Grammr { }

namespace Grammr.Lexers { }

namespace Grammr.Parsers { }

namespace Grammr.Syntax { }

namespace Grammr.Text { }

namespace Harmony { }

namespace HarmonyLib { }

namespace HarmonyLib.Internal { }

namespace HarmonyLib.Internal.Patching { }

namespace HarmonyLib.Internal.RuntimeFixes { }

namespace HarmonyLib.Internal.Util { }

namespace HarmonyLib.Public { }

namespace HarmonyLib.Public.Patching { }

namespace HarmonyLib.Tools { }

namespace ILMerge { }

namespace Iced { }

namespace Iced.Intel { }

namespace Iced.Intel.BlockEncoderInternal { }

namespace Iced.Intel.DecoderInternal { }

namespace Iced.Intel.EncoderInternal { }

namespace Iced.Intel.FastFormatterInternal { }

namespace Iced.Intel.FormatterInternal { }

namespace Iced.Intel.GasFormatterInternal { }

namespace Iced.Intel.InstructionInfoInternal { }

namespace Iced.Intel.IntelFormatterInternal { }

namespace Iced.Intel.Internal { }

namespace Iced.Intel.MasmFormatterInternal { }

namespace Iced.Intel.NasmFormatterInternal { }

namespace Il2Cpp { }

namespace Il2CppAOT { }

namespace Il2CppInternal { }

namespace Il2CppInternal.Cryptography { }

namespace Il2CppInternal.Runtime { }

namespace Il2CppInternal.Runtime.Augments { }

namespace Il2CppInternal.Threading { }

namespace Il2CppInternal.Threading.Tasks { }

namespace Il2CppInternal.Threading.Tasks.Tracing { }

namespace Il2CppInterop { }

namespace Il2CppInterop.Common { }

namespace Il2CppInterop.Common.Attributes { }

namespace Il2CppInterop.Common.Extensions { }

namespace Il2CppInterop.Common.Host { }

namespace Il2CppInterop.Common.Maps { }

namespace Il2CppInterop.Common.XrefScans { }

namespace Il2CppInterop.Generator { }

namespace Il2CppInterop.Generator.Contexts { }

namespace Il2CppInterop.Generator.Extensions { }

namespace Il2CppInterop.Generator.MetadataAccess { }

namespace Il2CppInterop.Generator.Passes { }

namespace Il2CppInterop.Generator.Runners { }

namespace Il2CppInterop.Generator.Utils { }

namespace Il2CppInterop.Generator.XrefScans { }

namespace Il2CppInterop.HarmonySupport { }

namespace Il2CppInterop.Runtime { }

namespace Il2CppInterop.Runtime.Attributes { }

namespace Il2CppInterop.Runtime.Injection { }

namespace Il2CppInterop.Runtime.Injection.Hooks { }

namespace Il2CppInterop.Runtime.InteropTypes { }

namespace Il2CppInterop.Runtime.InteropTypes.Arrays { }

namespace Il2CppInterop.Runtime.InteropTypes.Fields { }

namespace Il2CppInterop.Runtime.Runtime { }

namespace Il2CppInterop.Runtime.Runtime.VersionSpecific { }

namespace Il2CppInterop.Runtime.Runtime.VersionSpecific.Assembly { }

namespace Il2CppInterop.Runtime.Runtime.VersionSpecific.AssemblyName { }

namespace Il2CppInterop.Runtime.Runtime.VersionSpecific.Class { }

namespace Il2CppInterop.Runtime.Runtime.VersionSpecific.EventInfo { }

namespace Il2CppInterop.Runtime.Runtime.VersionSpecific.Exception { }

namespace Il2CppInterop.Runtime.Runtime.VersionSpecific.FieldInfo { }

namespace Il2CppInterop.Runtime.Runtime.VersionSpecific.Image { }

namespace Il2CppInterop.Runtime.Runtime.VersionSpecific.MethodInfo { }

namespace Il2CppInterop.Runtime.Runtime.VersionSpecific.ParameterInfo { }

namespace Il2CppInterop.Runtime.Runtime.VersionSpecific.PropertyInfo { }

namespace Il2CppInterop.Runtime.Runtime.VersionSpecific.Type { }

namespace Il2CppInterop.Runtime.Startup { }

namespace Il2CppInterop.Runtime.XrefScans { }

namespace Il2CppJetBrains { }

namespace Il2CppJetBrains.Annotations { }

namespace Il2CppMicrosoft { }

namespace Il2CppMicrosoft.CodeAnalysis { }

namespace Il2CppMicrosoft.Win32 { }

namespace Il2CppMicrosoft.Win32.SafeHandles { }

namespace Il2CppMono { }

namespace Il2CppMono.Globalization { }

namespace Il2CppMono.Globalization.Unicode { }

namespace Il2CppMono.Interop { }

namespace Il2CppMono.Security { }

namespace Il2CppMono.Security.Cryptography { }

namespace Il2CppMono.Xml { }

namespace Il2CppTMPro { }

namespace Il2CppTMPro.SpriteAssetUtilities { }

namespace Il2CppVarietyFX { }

namespace Il2Cppcom { }

namespace Il2Cppcom.cyborgAssets { }

namespace Il2Cppcom.cyborgAssets.inspectorButtonPro { }

namespace Il2Cppcom.cyborgAssets.internalIBP { }

namespace Il2Cppcom.cyborgAssets.internalIBPExample { }

namespace InlineIL { }

namespace InlineMethod { }

namespace Internal { }

namespace Internal.Cryptography { }

namespace JetBrains { }

namespace JetBrains.Annotations { }

namespace LZ4ps { }

namespace LocalsInit { }

namespace MelonLoader { }

namespace MelonLoader.Assertions { }

namespace MelonLoader.Bootstrap { }

namespace MelonLoader.CoreClrUtils { }

namespace MelonLoader.Fixes { }

namespace MelonLoader.ICSharpCode { }

namespace MelonLoader.ICSharpCode.SharpZipLib { }

namespace MelonLoader.ICSharpCode.SharpZipLib.BZip2 { }

namespace MelonLoader.ICSharpCode.SharpZipLib.Checksum { }

namespace MelonLoader.ICSharpCode.SharpZipLib.Core { }

namespace MelonLoader.ICSharpCode.SharpZipLib.Encryption { }

namespace MelonLoader.ICSharpCode.SharpZipLib.GZip { }

namespace MelonLoader.ICSharpCode.SharpZipLib.Lzw { }

namespace MelonLoader.ICSharpCode.SharpZipLib.Tar { }

namespace MelonLoader.ICSharpCode.SharpZipLib.Zip { }

namespace MelonLoader.ICSharpCode.SharpZipLib.Zip.Compression { }

namespace MelonLoader.ICSharpCode.SharpZipLib.Zip.Compression.Streams { }

namespace MelonLoader.InternalUtils { }

namespace MelonLoader.Lemons { }

namespace MelonLoader.Lemons.Cryptography { }

namespace MelonLoader.Logging { }

namespace MelonLoader.Melons { }

namespace MelonLoader.Modules { }

namespace MelonLoader.MonoInternals { }

namespace MelonLoader.NativeHost { }

namespace MelonLoader.NativeUtils { }

namespace MelonLoader.NativeUtils.PEParser { }

namespace MelonLoader.Pastel { }

namespace MelonLoader.Preferences { }

namespace MelonLoader.Preferences.IO { }

namespace MelonLoader.Resolver { }

namespace MelonLoader.TinyJSON { }

namespace MelonLoader.Utils { }

namespace Microsoft { }

namespace Microsoft.CSharp { }

namespace Microsoft.CSharp.RuntimeBinder { }

namespace Microsoft.Cci { }

namespace Microsoft.Cci.Pdb { }

namespace Microsoft.CodeAnalysis { }

namespace Microsoft.CodeAnalysis.AddImport { }

namespace Microsoft.CodeAnalysis.CaseCorrection { }

namespace Microsoft.CodeAnalysis.ChangeNamespace { }

namespace Microsoft.CodeAnalysis.Classification { }

namespace Microsoft.CodeAnalysis.Classification.Classifiers { }

namespace Microsoft.CodeAnalysis.CodeActions { }

namespace Microsoft.CodeAnalysis.CodeCleanup { }

namespace Microsoft.CodeAnalysis.CodeCleanup.Providers { }

namespace Microsoft.CodeAnalysis.CodeFixes { }

namespace Microsoft.CodeAnalysis.CodeFixesAndRefactorings { }

namespace Microsoft.CodeAnalysis.CodeGen { }

namespace Microsoft.CodeAnalysis.CodeGeneration { }

namespace Microsoft.CodeAnalysis.CodeRefactorings { }

namespace Microsoft.CodeAnalysis.CodeStyle { }

namespace Microsoft.CodeAnalysis.Collections { }

namespace Microsoft.CodeAnalysis.Collections.Internal { }

namespace Microsoft.CodeAnalysis.Debugging { }

namespace Microsoft.CodeAnalysis.Diagnostics { }

namespace Microsoft.CodeAnalysis.Diagnostics.Analyzers { }

namespace Microsoft.CodeAnalysis.Diagnostics.Analyzers.NamingStyles { }

namespace Microsoft.CodeAnalysis.Diagnostics.Telemetry { }

namespace Microsoft.CodeAnalysis.Differencing { }

namespace Microsoft.CodeAnalysis.Editing { }

namespace Microsoft.CodeAnalysis.EditorConfig { }

namespace Microsoft.CodeAnalysis.EditorConfig.Parsing { }

namespace Microsoft.CodeAnalysis.EditorConfig.Parsing.NamingStyles { }

namespace Microsoft.CodeAnalysis.EmbeddedLanguages { }

namespace Microsoft.CodeAnalysis.EmbeddedLanguages.Common { }

namespace Microsoft.CodeAnalysis.EmbeddedLanguages.VirtualChars { }

namespace Microsoft.CodeAnalysis.Emit { }

namespace Microsoft.CodeAnalysis.Emit.EditAndContinue { }

namespace Microsoft.CodeAnalysis.Emit.NoPia { }

namespace Microsoft.CodeAnalysis.ErrorLogger { }

namespace Microsoft.CodeAnalysis.ErrorReporting { }

namespace Microsoft.CodeAnalysis.Extensions { }

namespace Microsoft.CodeAnalysis.ExternalAccess { }

namespace Microsoft.CodeAnalysis.ExternalAccess.Pythia { }

namespace Microsoft.CodeAnalysis.ExternalAccess.Pythia.Api { }

namespace Microsoft.CodeAnalysis.ExternalAccess.UnitTesting { }

namespace Microsoft.CodeAnalysis.ExternalAccess.UnitTesting.Api { }

namespace Microsoft.CodeAnalysis.ExternalAccess.VSTypeScript { }

namespace Microsoft.CodeAnalysis.ExternalAccess.VSTypeScript.Api { }

namespace Microsoft.CodeAnalysis.ExtractMethod { }

namespace Microsoft.CodeAnalysis.FindSymbols { }

namespace Microsoft.CodeAnalysis.FindSymbols.FindReferences { }

namespace Microsoft.CodeAnalysis.FindSymbols.Finders { }

namespace Microsoft.CodeAnalysis.FindSymbols.SymbolTree { }

namespace Microsoft.CodeAnalysis.FlowAnalysis { }

namespace Microsoft.CodeAnalysis.FlowAnalysis.SymbolUsageAnalysis { }

namespace Microsoft.CodeAnalysis.Formatting { }

namespace Microsoft.CodeAnalysis.Formatting.Rules { }

namespace Microsoft.CodeAnalysis.GeneratedCodeRecognition { }

namespace Microsoft.CodeAnalysis.Host { }

namespace Microsoft.CodeAnalysis.Host.Mef { }

namespace Microsoft.CodeAnalysis.Indentation { }

namespace Microsoft.CodeAnalysis.InitializeParameter { }

namespace Microsoft.CodeAnalysis.Internal { }

namespace Microsoft.CodeAnalysis.Internal.Log { }

namespace Microsoft.CodeAnalysis.InternalUtilities { }

namespace Microsoft.CodeAnalysis.Interop { }

namespace Microsoft.CodeAnalysis.LanguageService { }

namespace Microsoft.CodeAnalysis.LanguageService.TypeInferenceService { }

namespace Microsoft.CodeAnalysis.MoveDeclarationNearReference { }

namespace Microsoft.CodeAnalysis.NamingStyles { }

namespace Microsoft.CodeAnalysis.Notification { }

namespace Microsoft.CodeAnalysis.ObsoleteSymbol { }

namespace Microsoft.CodeAnalysis.Operations { }

namespace Microsoft.CodeAnalysis.Options { }

namespace Microsoft.CodeAnalysis.OrganizeImports { }

namespace Microsoft.CodeAnalysis.Packaging { }

namespace Microsoft.CodeAnalysis.PatternMatching { }

namespace Microsoft.CodeAnalysis.PooledObjects { }

namespace Microsoft.CodeAnalysis.Precedence { }

namespace Microsoft.CodeAnalysis.Progress { }

namespace Microsoft.CodeAnalysis.ProjectSystem { }

namespace Microsoft.CodeAnalysis.ReassignedVariable { }

namespace Microsoft.CodeAnalysis.Recommendations { }

namespace Microsoft.CodeAnalysis.Remote { }

namespace Microsoft.CodeAnalysis.RemoveUnnecessaryImports { }

namespace Microsoft.CodeAnalysis.Rename { }

namespace Microsoft.CodeAnalysis.Rename.ConflictEngine { }

namespace Microsoft.CodeAnalysis.ReplaceDiscardDeclarationsWithAssignments { }

namespace Microsoft.CodeAnalysis.RuntimeMembers { }

namespace Microsoft.CodeAnalysis.SQLite { }

namespace Microsoft.CodeAnalysis.SQLite.Interop { }

namespace Microsoft.CodeAnalysis.SQLite.v2 { }

namespace Microsoft.CodeAnalysis.SQLite.v2.Interop { }

namespace Microsoft.CodeAnalysis.SemanticModelReuse { }

namespace Microsoft.CodeAnalysis.Serialization { }

namespace Microsoft.CodeAnalysis.Shared { }

namespace Microsoft.CodeAnalysis.Shared.CodeStyle { }

namespace Microsoft.CodeAnalysis.Shared.Collections { }

namespace Microsoft.CodeAnalysis.Shared.Extensions { }

namespace Microsoft.CodeAnalysis.Shared.Extensions.ContextQuery { }

namespace Microsoft.CodeAnalysis.Shared.Helpers { }

namespace Microsoft.CodeAnalysis.Shared.Helpers.RemoveUnnecessaryImports { }

namespace Microsoft.CodeAnalysis.Shared.Naming { }

namespace Microsoft.CodeAnalysis.Shared.TestHooks { }

namespace Microsoft.CodeAnalysis.Shared.Utilities { }

namespace Microsoft.CodeAnalysis.Simplification { }

namespace Microsoft.CodeAnalysis.Simplification.Simplifiers { }

namespace Microsoft.CodeAnalysis.SolutionCrawler { }

namespace Microsoft.CodeAnalysis.SourceGeneration { }

namespace Microsoft.CodeAnalysis.SourceGeneratorTelemetry { }

namespace Microsoft.CodeAnalysis.Storage { }

namespace Microsoft.CodeAnalysis.SymbolDisplay { }

namespace Microsoft.CodeAnalysis.SymbolSearch { }

namespace Microsoft.CodeAnalysis.Symbols { }

namespace Microsoft.CodeAnalysis.Syntax { }

namespace Microsoft.CodeAnalysis.Syntax.InternalSyntax { }

namespace Microsoft.CodeAnalysis.Tags { }

namespace Microsoft.CodeAnalysis.TaskList { }

namespace Microsoft.CodeAnalysis.Telemetry { }

namespace Microsoft.CodeAnalysis.Text { }

namespace Microsoft.CodeAnalysis.UnitTests { }

namespace Microsoft.CodeAnalysis.Utilities { }

namespace Microsoft.CodeAnalysis.VisualBasic { }

namespace Microsoft.CodeAnalysis.VisualBasic.CodeGeneration { }

namespace Microsoft.CodeAnalysis.VisualBasic.CodeStyle { }

namespace Microsoft.CodeAnalysis.VisualBasic.Formatting { }

namespace Microsoft.CodeAnalysis.VisualBasic.Simplification { }

namespace Microsoft.CodeAnalysis.Workspaces { }

namespace Microsoft.CodeAnalysis.Workspaces.Diagnostics { }

namespace Microsoft.CodeAnalysis.Workspaces.ProjectSystem { }

namespace Microsoft.DiaSymReader { }

namespace Microsoft.Diagnostics { }

namespace Microsoft.Diagnostics.NETCore { }

namespace Microsoft.Diagnostics.NETCore.Client { }

namespace Microsoft.Diagnostics.NETCore.Client.WebSocketServer { }

namespace Microsoft.Diagnostics.Runtime { }

namespace Microsoft.Diagnostics.Runtime.AbstractDac { }

namespace Microsoft.Diagnostics.Runtime.DacImplementation { }

namespace Microsoft.Diagnostics.Runtime.DacInterface { }

namespace Microsoft.Diagnostics.Runtime.DataReaders { }

namespace Microsoft.Diagnostics.Runtime.DataReaders.Implementation { }

namespace Microsoft.Diagnostics.Runtime.DataReaders.Windows { }

namespace Microsoft.Diagnostics.Runtime.DbgEng { }

namespace Microsoft.Diagnostics.Runtime.Extensions { }

namespace Microsoft.Diagnostics.Runtime.Implementation { }

namespace Microsoft.Diagnostics.Runtime.Interfaces { }

namespace Microsoft.Diagnostics.Runtime.MacOS { }

namespace Microsoft.Diagnostics.Runtime.MacOS.Structs { }

namespace Microsoft.Diagnostics.Runtime.Utilities { }

namespace Microsoft.Diagnostics.Runtime.Windows { }

namespace Microsoft.Extensions { }

namespace Microsoft.Extensions.Configuration { }

namespace Microsoft.Extensions.Configuration.Binder { }

namespace Microsoft.Extensions.Configuration.Memory { }

namespace Microsoft.Extensions.DependencyInjection { }

namespace Microsoft.Extensions.DependencyInjection.Abstractions { }

namespace Microsoft.Extensions.DependencyInjection.Extensions { }

namespace Microsoft.Extensions.Internal { }

namespace Microsoft.Extensions.Logging { }

namespace Microsoft.Extensions.Logging.Abstractions { }

namespace Microsoft.Extensions.Options { }

namespace Microsoft.Extensions.Primitives { }

namespace Microsoft.SqlServer { }

namespace Microsoft.SqlServer.Server { }

namespace Microsoft.VisualBasic { }

namespace Microsoft.VisualBasic.CompilerServices { }

namespace Microsoft.VisualBasic.FileIO { }

namespace Microsoft.Win32 { }

namespace Microsoft.Win32.SafeHandles { }

namespace Mono { }

namespace Mono.Cecil { }

namespace Mono.Cecil.Cil { }

namespace Mono.Cecil.Mdb { }

namespace Mono.Cecil.Metadata { }

namespace Mono.Cecil.PE { }

namespace Mono.Cecil.Pdb { }

namespace Mono.Cecil.Rocks { }

namespace Mono.Collections { }

namespace Mono.Collections.Generic { }

namespace Mono.CompilerServices { }

namespace Mono.CompilerServices.SymbolWriter { }

namespace Mono.Security { }

namespace Mono.Security.Cryptography { }

namespace MonoMod { }

namespace MonoMod.Backports { }

namespace MonoMod.Backports.ILHelpers { }

namespace MonoMod.Cil { }

namespace MonoMod.InlineRT { }

namespace MonoMod.ModInterop { }

namespace MonoMod.RuntimeDetour { }

namespace MonoMod.RuntimeDetour.HookGen { }

namespace MonoMod.RuntimeDetour.Platforms { }

namespace MonoMod.SourceGen { }

namespace MonoMod.SourceGen.Attributes { }

namespace MonoMod.Utils { }

namespace MonoMod.Utils.Cil { }

namespace Newtonsoft { }

namespace Newtonsoft.Json { }

namespace Newtonsoft.Json.Bson { }

namespace Newtonsoft.Json.Converters { }

namespace Newtonsoft.Json.Linq { }

namespace Newtonsoft.Json.Linq.JsonPath { }

namespace Newtonsoft.Json.Schema { }

namespace Newtonsoft.Json.Serialization { }

namespace Newtonsoft.Json.Utilities { }

namespace NullGuard { }

namespace NullGuard.CodeAnalysis { }

namespace Roslyn { }

namespace Roslyn.Utilities { }

namespace Scifa { }

namespace Scifa.CheckedExceptions { }

namespace Scifa.CheckedExceptions.Attributes { }

namespace Semver { }

namespace SevenZip { }

namespace SevenZip.Buffer { }

namespace SevenZip.CommandLineParser { }

namespace SevenZip.Compression { }

namespace SevenZip.Compression.LZ { }

namespace SevenZip.Compression.LZMA { }

namespace SevenZip.Compression.RangeCoder { }

namespace Tomlet { }

namespace Tomlet.Attributes { }

namespace Tomlet.Exceptions { }

namespace Tomlet.Extensions { }

namespace Tomlet.Models { }

namespace Trowel { }

namespace Unity { }

namespace Unity.Audio { }

namespace Unity.Baselib { }

namespace Unity.Baselib.LowLevel { }

namespace Unity.Burst { }

namespace Unity.Burst.CompilerServices { }

namespace Unity.Burst.Intrinsics { }

namespace Unity.Burst.LowLevel { }

namespace Unity.Collections { }

namespace Unity.Collections.LowLevel { }

namespace Unity.Collections.LowLevel.Unsafe { }

namespace Unity.Collections.LowLevel.Unsafe.NotBurstCompatible { }

namespace Unity.Collections.NotBurstCompatible { }

namespace Unity.Curl { }

namespace Unity.IL2CPP { }

namespace Unity.IL2CPP.CompilerServices { }

namespace Unity.IL2CPP.Metadata { }

namespace Unity.IO { }

namespace Unity.IO.Archive { }

namespace Unity.IO.LowLevel { }

namespace Unity.IO.LowLevel.Unsafe { }

namespace Unity.Jobs { }

namespace Unity.Jobs.LowLevel { }

namespace Unity.Jobs.LowLevel.Unsafe { }

namespace Unity.Loading { }

namespace Unity.Mathematics { }

namespace Unity.Mathematics.Geometry { }

namespace Unity.Profiling { }

namespace Unity.Profiling.LowLevel { }

namespace Unity.Profiling.LowLevel.Unsafe { }

namespace Unity.Profiling.Memory { }

namespace Unity.Properties { }

namespace Unity.Properties.Internal { }

namespace Unity.SpriteShape { }

namespace Unity.SpriteShape.External { }

namespace Unity.SpriteShape.External.LibTessDotNet { }

namespace Unity.TLS { }

namespace Unity.TLS.LowLevel { }

namespace UnityEditor { }

namespace UnityEditor.Experimental { }

namespace UnityEditor.Rendering { }

namespace UnityEditor.Rendering.BuiltIn { }

namespace UnityEditor.Rendering.BuiltIn.ShaderGraph { }

namespace UnityEditor.Rendering.Universal { }

namespace UnityEngine { }

namespace UnityEngine.AI { }

namespace UnityEngine.Accessibility { }

namespace UnityEngine.Advertisements { }

namespace UnityEngine.Analytics { }

namespace UnityEngine.Android { }

namespace UnityEngine.Animations { }

namespace UnityEngine.Apple { }

namespace UnityEngine.Assertions { }

namespace UnityEngine.Assertions.Comparers { }

namespace UnityEngine.Assertions.Must { }

namespace UnityEngine.Audio { }

namespace UnityEngine.Bindings { }

namespace UnityEngine.Connect { }

namespace UnityEngine.CrashReportHandler { }

namespace UnityEngine.Device { }

namespace UnityEngine.Diagnostics { }

namespace UnityEngine.EventSystems { }

namespace UnityEngine.Events { }

namespace UnityEngine.Experimental { }

namespace UnityEngine.Experimental.AI { }

namespace UnityEngine.Experimental.Animations { }

namespace UnityEngine.Experimental.AssetBundlePatching { }

namespace UnityEngine.Experimental.Audio { }

namespace UnityEngine.Experimental.GlobalIllumination { }

namespace UnityEngine.Experimental.Playables { }

namespace UnityEngine.Experimental.Rendering { }

namespace UnityEngine.Experimental.Rendering.RenderGraphModule { }

namespace UnityEngine.Experimental.Rendering.Universal { }

namespace UnityEngine.Experimental.U2D { }

namespace UnityEngine.Experimental.VFX { }

namespace UnityEngine.Experimental.Video { }

namespace UnityEngine.Experimental.XR { }

namespace UnityEngine.IO { }

namespace UnityEngine.Internal { }

namespace UnityEngine.Jobs { }

namespace UnityEngine.LowLevel { }

namespace UnityEngine.Lumin { }

namespace UnityEngine.Networking { }

namespace UnityEngine.Networking.PlayerConnection { }

namespace UnityEngine.ParticleSystemJobs { }

namespace UnityEngine.Playables { }

namespace UnityEngine.PlayerLoop { }

namespace UnityEngine.Pool { }

namespace UnityEngine.Profiling { }

namespace UnityEngine.Rendering { }

namespace UnityEngine.Rendering.LookDev { }

namespace UnityEngine.Rendering.RendererUtils { }

namespace UnityEngine.Rendering.UI { }

namespace UnityEngine.Rendering.Universal { }

namespace UnityEngine.Rendering.Universal.Internal { }

namespace UnityEngine.Rendering.Universal.LibTessDotNet { }

namespace UnityEngine.Rendering.Universal.UTess { }

namespace UnityEngine.SceneManagement { }

namespace UnityEngine.Scripting { }

namespace UnityEngine.Scripting.APIUpdating { }

namespace UnityEngine.Search { }

namespace UnityEngine.SearchService { }

namespace UnityEngine.Serialization { }

namespace UnityEngine.SocialPlatforms { }

namespace UnityEngine.SocialPlatforms.Impl { }

namespace UnityEngine.Sprites { }

namespace UnityEngine.Subsystems { }

namespace UnityEngine.SubsystemsImplementation { }

namespace UnityEngine.SubsystemsImplementation.Extensions { }

namespace UnityEngine.TerrainTools { }

namespace UnityEngine.TerrainUtils { }

namespace UnityEngine.TestTools { }

namespace UnityEngine.TextCore { }

namespace UnityEngine.TextCore.LowLevel { }

namespace UnityEngine.TextCore.Text { }

namespace UnityEngine.Tilemaps { }

namespace UnityEngine.U2D { }

namespace UnityEngine.U2D.Animation { }

namespace UnityEngine.U2D.Common { }

namespace UnityEngine.U2D.Common.UTess { }

namespace UnityEngine.UI { }

namespace UnityEngine.UI.Collections { }

namespace UnityEngine.UI.CoroutineTween { }

namespace UnityEngine.UIElements { }

namespace UnityEngine.UIElements.Collections { }

namespace UnityEngine.UIElements.Experimental { }

namespace UnityEngine.UIElements.Internal { }

namespace UnityEngine.UIElements.StyleSheets { }

namespace UnityEngine.UIElements.StyleSheets.Syntax { }

namespace UnityEngine.UIElements.UIR { }

namespace UnityEngine.UIElements.UIR.Implementation { }

namespace UnityEngine.VFX { }

namespace UnityEngine.Video { }

namespace UnityEngine.Windows { }

namespace UnityEngine.Windows.Speech { }

namespace UnityEngine.Windows.WebCam { }

namespace UnityEngine.XR { }

namespace UnityEngine.XR.Provider { }

namespace UnityEngine.XR.Tango { }

namespace UnityEngine.XR.WSA { }

namespace UnityEngine.XR.WSA.Input { }

namespace UnityEngine.Yoga { }

namespace UnityEngine._Scripting { }

namespace UnityEngine._Scripting.APIUpdating { }

namespace UnityEngineInternal { }

namespace UnityEngineInternal.Input { }

namespace UnityEngineInternal.Video { }

namespace UnityEngineInternal.XR { }

namespace UnityEngineInternal.XR.WSA { }

namespace WebSocketDotNet { }

namespace WebSocketDotNet.Http { }

namespace WebSocketDotNet.Messages { }

namespace WebSocketDotNet.Protocol { }

namespace WebSocketDotNet.Utils { }

namespace bHapticsLib { }

namespace bHapticsLib.Internal { }

namespace bHapticsLib.Internal.Models { }

namespace bHapticsLib.Internal.Models.Connection { }

namespace bHapticsLib.Internal.SimpleJSON { }

namespace bHapticsLib.Properties { }
